# Custom docker image at: https://github.com/nud3l/sphinx-latex-docker
image: dominik0int/sphinx

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
    - python3 -V  # Print out python version for debugging
    - pip3 install -r requirements.txt

btcrelay:
    stage: test
    script:
    - cd btcrelay-spec/docs; make html
    - sphinx-build -b latex source build/latex
    - make -C build/latex  
    only:
    - branches
    except:
    - master

polkabtc:
    stage: test
    script:
    - cd polkabtc-spec/docs; make html
    - sphinx-build -b latex source build/latex
    - make -C build/latex    
    only:
    - branches
    except:
    - master

pages:
    stage: deploy
    script:
    - cd btcrelay-spec/docs
    - make html
    - sphinx-build -b latex source build/latex
    - make -C build/latex
    - mv build/html/ ../../public/btcrelay-spec/
    - mv build/latex/BTCRelay.pdf ../../public/btcrelay-spec.pdf
    - cd ../..
    - cd polkabtc-spec/docs
    - make html
    - sphinx-build -b latex source build/latex
    - make -C build/latex
    - mv build/html/* ../../public/
    - mv build/latex/PolkaBTC.pdf ../../public/polkabtc-spec.pdf
    artifacts:
        paths:
        - public
    only:
    - master
    
